name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  bzlmod-lock:
    uses: eclipse-score/cicd-workflows/.github/workflows/bzlmod-lock-check.yml@bzlmod-lock-check/v0.0.0
